{% set name = "deprecation-alias" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deprecation-alias-{{ version }}.tar.gz
  sha256: 1c9e1a5ddd0a276a1a18e7a4f9d56b53232217491c4549eaa45e51753013ce76

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - deprecation >=2.1.0
    - packaging >=20.4
    - python >=3.6

test:
  imports:
    - deprecation_alias
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/domdfcoding/deprecation-alias
  summary: A wrapper around 'deprecation' providing support for deprecated aliases.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - domdfcoding
